### ISSUE TITLE
Greetings.

### ISSUE THREAD

**Issue by UnlimtedPlugins** [Bevelio/UltraGames#1]
Hello sir i was wondering if you could show us how an arena is setup and could you create a kit with a perk ? Thank you

**Comment by Bevelio** [comment]
Hey man, sure thing!
I update the readme file to include how to create a new arena. :D

https://github.com/Bevelio/UltraGames#create-an-arena

but pretty much you just create a new world, build a few things on it and then add the world config files to it and zip it up

**Comment by Bevelio** [comment]
Also it is possible to create a kit with a perk but I do not have any perks create. if you would like to suggest one, I'll be happy to make it!

**Comment by UnlimtedPlugins** [comment]
I was thinking of the perk berserker :p and i have noticed kits are created through config ? Then how can i add a perk to a kit through config ? Do you mind showing us :)
